### ISSUE TITLE
Tesla Supercharger vs Destination Charger incorrect "upgrade"

### ISSUE THREAD

**Issue by mxxcon** [osmlab/name-suggestion-index#9143] opened 2024-01-13 01:11 UTC
When I create Tesla Supercharger node iD/RapiD prompts me to "upgrade" it to Tesla Destination Charger.
![image](https://github.com/osmlab/name-suggestion-index/assets/847140/a2f5e296-ad27-4ece-b139-6b74b59acad2)

https://nsi.guide/index.html?t=brands&k=man_made&v=charge_point&tt=tesla
`teslasupercharger-9b2e7d`
`teslainc-9b2e7d`
They are not "upgrade" of each other. They are different things.

**Comment by AntiCompositeNumber** [comment] 2024-01-13 01:49
Duplicate of #8237

**Closed by AntiCompositeNumber** 2024-01-13 01:49 UTC
