### ISSUE TITLE
Fix "Цех 85 54c425-1c12ef

### ISSUE THREAD

**Issue by afanasovich** [osmlab/name-suggestion-index#5717] opened 2021-11-22 16:19 UTC
amenity=cafe
contact:email=info@tseh85.ru
contact:instagram=https://instagram.com/tseh85
contact:phone=+7 812 7757785
contact:vk=https://vk.com/tseh85
contact:website=https://tseh85.ru
name=Цех 85
opening_hours=Mo-Su 08:00-22:00
opening_hours:covid19=same
operator=Щеглова
payment:cash=yes
payment:credit_cards=yes
payment:debit_cards=yes
shop=bakery

**Comment by arch0345** [comment] 2021-11-22 18:51
Duplicate of #5718

**Closed by arch0345** 2021-11-22 18:51 UTC
