### ISSUE TITLE
Add: Halfords (The Netherlands)

### ISSUE THREAD

**Issue by boothym** [osmlab/name-suggestion-index#3889] opened 2020-05-27 21:54 UTC
Could someone please add service:bicycle:repair=yes to Halfords, as their shops do bike repairs as well.

I also noticed from an overpass turbo query that there are a number of Halfords shop in the Netherlands https://www.halfords.nl/ https://nl.wikipedia.org/wiki/Halfords

Wonder if these should have different wikidata and wikipedia to the UK & IRL shops?

**Comment by SilentSpike** [comment] 2020-05-27 22:52
Do *all* of their shops do repair?

I think the NL brand is different, looks to have a different logo.

**Comment by boothym** [comment] 2020-05-28 12:36
It seems like it - go to https://www.halfords.com/locations uncheck garage and pickup point, then search for some random locations - all the ones I've seen have bike repair listed under services.

**Comment by UKChris-osm** [comment] 2020-05-31 09:29
The Halfords web site shows "_424_" retail stores in total on the locations page, and when using the "_byicycle repair_" filter this remains at "_424_", which to me confirms they do bicycle repair in all stores.

**Comment by UKChris-osm** [comment] 2020-05-31 09:36
Halfords in The Netherlands used to be part of the Halfords UK brand, but is now a separate company, and so should have its own entry in the NSI.

Looking at it though, I get the feeling they are more of a bicycle retail chain that also does car parts, compered to the UK chain that's more of a car parts retailer with cycling as an added extra.

**Comment by Adamant36** [comment] 2020-06-01 07:48
> I've added service:bicycle:repair=yes to Halfords.

I'm not sure adding a bicycle repair tag is a good idea. Since it doesn't seem like all their locations provide the service. Otherwise, they wouldn't have a filter for it in their location search to find ones that do.

**Comment by UKChris-osm** [comment] 2020-06-01 07:56
> I'm not sure adding a bicycle repair tag is a good idea. Since it doesn't seem like all their locations provide the service. Otherwise, they wouldn't have a filter for it in their location search to find ones that do.

I'll happily remove it if it's deemed not suitable @Adamant36 

However, I am confident all the Halfords shops listed as "shop/car_parts" do have bicycle repairs, based on the filter.

The Halfords web site lists both general Halfords shops, and the "Halfords AutoCentre", which is why I think the filter exists. I first removed all "Autocentres", which listed the remaining general Halfords stores as having "424", then selecting the bicycle repair filter remained with "424" stores listed, which to me tells me all Halfords within "shop/car_parts" do have bicycle repair facilities, whereas the Autocentres do not.

**Comment by Adamant36** [comment] 2020-06-01 09:42
It seems that the UK shop/car_parts|Halfords brand is already tagged with service:bicycle:retail. This whole namespace thing is non-nonsensical and redundant. 

> However, I am confident all the Halfords shops listed as "shop/car_parts" do have bicycle repairs, based on the filter.

So, add it for the car parts shops and not the repair ones, I guess. Although, I find it hard to believe you couldn't walk into an auto center and have them pump up your tube, or use a wrench to tighten something on it if you asked to. Especially if you bought the bicycle at one of their locations. Which is another reason I'm against this kind of tagging. Aside from it just being ridiculously obtuse. 

For example I'd love to know the distinction that they make in their locations filter between bicycle "service", bicycle "repair", and bicycle "check" is. In America they are essentially the same thing and I find it hard to believe any location that does bicycle repair also doesn't do checks or service. Yet they still have a filter for them. So, they must be different some how. Although, we aren't making them different by using a tag with both the words service and repair in it. So, I don't know. Can we assume all shops do both service and repair (why would their be a filter for it if so)? Or use a single tag for both? What's the difference anyway?

**Comment by Adamant36** [comment] 2020-06-01 09:52
They should really just extend the amenity=bicycle_repair tag to include shops.

**Comment by UKChris-osm** [comment] 2020-06-01 12:25
I don't really have a definitive opinion either way, so sorry if my view below isn't overly helpful.

I always did think that the NSI was really about names, key/value type & brand only (and previously operator), and so extra tagging wasn't something I thought was really done, but after seeing the [Premier Inn Wifi](https://github.com/osmlab/name-suggestion-index/pull/3910) tags added, and seeing that Halfords, like you said @Adamant36, already had "_[service:bicycle:retail](https://wiki.openstreetmap.org/wiki/Key:service:bicycle:retail)_" in the index, then the additional repair value didn't seem out of place if it applied to all Halfords retails stores.

I contacted Halfords, and they confirmed all stores have a bicycle repair service, as well as selling bikes, so I think both tags could remain in that sense.

> For example I'd love to know the distinction that they make in their locations filter between bicycle "service", bicycle "repair", and bicycle "check" is.

I think you're right that, in the everyday sense, they would all be the same thing.

What I hadn't realised was that there are stores branded as "_Halfords Metro_", which do bicycle repair, but not checking or servicing. Even though I'g agree that checks and servicing are similar to a repair, maybe the Metro stores just offer a limited range due to space / staff.

You probably could walk into an Autocentre and ask for assistance, but as it isn't something that is advertised as being offered from Autocentres, then I wouldn't consider it correct to add any such tag, whereas Halfords Retails stores explicitly do offer such a service.

I don't see any negative in "_[service:bicycle:retail](https://wiki.openstreetmap.org/wiki/Key:service:bicycle:retail)_" or "_[service:bicycle:repair](https://wiki.openstreetmap.org/wiki/Key:service:bicycle:repair)_" being a part of the Halfords retail entry (shop/car_parts) myself. They seem like legitimate OSM tags, defined in the OSM Wiki as existing, but would understand if they were removed from the NSI.

**Comment by Adamant36** [comment] 2020-06-01 14:52
> after seeing the Premier Inn Wifi tags added, and seeing that Halfords, like you said @Adamant36, already had "service:bicycle:retail" in the index, then the additional repair value didn't seem out of place if it applied to all Halfords retails stores.

Well, I didn't see that PR until just now and it's not one that I personally would have merged. I'm picker then a lot of people though. Plus, I can afford to burn through some social capital, that others can't or don't want to, by not merging everything. 

> I contacted Halfords, and they confirmed all stores have a bicycle repair service, as well as selling bikes, so I think both tags could remain in that sense.

Well, at least you have confirmation from them about it. My main issue is not trusting a search box. We have less room for error then a random companies web designer/database maintainer does IMO, but I'll go with the word of an actual contact. 

> What I hadn't realised was that there are stores branded as "Halfords Metro", which do bicycle repair, but not checking or servicing.

I guess we can create another entry for them then. There should be a way to tag the difference between service and repair, but it doesn't seem like there is with how things currently are. So, I guess repair is what we are stuck with. 

> You probably could walk into an Autocentre and ask for assistance, but as it isn't something that is advertised as being offered from Autocentres, then I wouldn't consider it correct to add any such tag

I agree. It was more just a general comment about the usage of these types of tags in the first place. I wouldn't advocate for adding service:bicycle:repair to the auto centers though. Although, now that I think about it, an "ask" type tag might kinda cool though.

> I don't see any negative in "service:bicycle:retail" or "service:bicycle:repair" being a part of the Halfords retail entry (shop/car_parts) myself. They seem like legitimate OSM tags, defined in the OSM Wiki as existing, but would understand if they were removed from the NSI.

uuhh, it's just, that, I really dislike namespaces. Especially in this case where it seems like a namespace just for it's own sake. Mostly my issue is with the usage of the word "retail." The meaning of it is really not intuitive at all. They should have gone with something like "sales" instead. I wouldn't call selling bikes in a store a "service" either. Anymore then it would be for anywhere else that sells multiple items to be providing a "service" for doing so. That's just how some shops work. They sell multiple things. I don't think it's worthy of a separate tag in most cases and from what I've seen having one leads to a lot of bad tagging (not that it will here). That's on the community for approving it though. 

I'm fine with service:bicycle:repair as long as it pans out that all the places provide bicycle repair. Which it seems like we have confirmation of. So, 👍

**Comment by boothym** [comment] 2020-06-04 20:28
>So, add it for the car parts shops and not the repair ones, I guess.

This PR was only ever about the car parts shops 😉 

>It seems that the UK shop/car_parts|Halfords brand is already tagged with service:bicycle:retail. This whole namespace thing is non-nonsensical and redundant.

Not really, the issue with Halfords is that a large chunk of its business is bicycles, so there needs to be a way to indicate that in OSM so long as we don't want it tagged shop=car_parts;bicycle.

**Comment by Adamant36** [comment] 2020-06-05 01:30
> This PR was only ever about the car parts shops

I know. Its called agreeing/discussion. I'm not sure what the issue with either is. 

> The issue with Halfords is that a large chunk of its business is bicycles, so there needs to be a way to indicate that in OSM

Really? and here I thought this issue was something completely unrelated to OpenStreetMap or bicycle. 


Anyway, no one ever floated using shop=car_parts;bicycle instead of the service namespace. What we usually do in those instances is use two seperate entries. So for example gas stations with convience stores or drug stores with pharmacys. What does the established way of doing things matter though? 

There was never tags like service:pharamcy:drug_dispening=yes/no to add to drug stores or service:convience_store=sure to add to gas stations and for good reason IMO. Let along that the OSM guidelines say things like that should be mapped seperately. My question is, how this is different from those examples to the point that we should go with the service namespace instead of established practices? Personally, if half their business is bicycles, then I split them into two different entries. Its what we already do in these types of situations. There's zero reason not to or to over complicate it with the namespaces pointlessly instead.

**Comment by Adamant36** [comment] 2020-09-11 05:05
I'm going to close this since it seems to be resolved. Feel free to re-open it if it's not though.

**Closed by Adamant36** 2020-09-11 05:05 UTC
Labels: add brand, good first issue, needs research, needs wikidata
