### ISSUE TITLE
Adding a "parent" country / region

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#5180] opened 2021-08-01 09:42 UTC
With many more entries now receiving a custom geojson or GPS locationSet, I see this makes using the Country Code search feature on [nsi.guide](https://nsi.guide) a lot less useful, as we can no longer search for entries in, say, Canada, that don't directly reference "_ca_" in the locationSet.

So, alongside "_note_", is there perhaps something we can add to reintroduce the ability to search for entries based on Country, such as 
{
"parentcountry": "ca",
"locationSet": {"include": [[[80.0,50.0,65](https://ideditor.github.io/location-conflation/?locationSet=%7B%22include%22%3A%5B%5B-80.0%2C50.0%2C65%5D%5D%7D&referrer=nsi)]]},
"note": "This entry is based a small town in Canada",
}

**Comment by peternewman** [comment] 2022-01-31 20:47
I think this is a duplicate of #4077 and personally I'm not sure that manually adding another tag is the right way to fix it (aside from it not fixing most of the other edge cases).

**Comment by bhousel** [comment] 2023-07-19 14:44
Yeah, I'm playing around with nsi.guide toady and thinking of ways to improve the country code search field.
I'd need to index all the geometries in order to search them properly, but that might be doable without too much trouble.
I'll keep #4077 open for now and close this one.

**Closed by bhousel** 2023-07-19 14:44 UTC
Labels: enhancement, question, locationSet, nsi.guide
