### ISSUE TITLE
Move shop/beauty|Yves Rocher to shop/cosmetics|Yves Rocher

### ISSUE THREAD

**Issue by KAMI911** [osmlab/name-suggestion-index#3604] opened 2020-03-15 07:33 UTC
Hi,
I think Yves Rocher is more like a shop than a saloon.
IMHO the shop=cosmetics tag is better describing the POI than the current
"beauty": "cosmetics"
"shop": "beauty"
tags.
https://nsi.guide/index.html?k=shop&v=cosmetics
https://wiki.openstreetmap.org/wiki/Tag:shop%3Dcosmetics

Thank you in advance!

Reference: https://github.com/KAMI911/osm_poi_matchmaker/issues/67

**Comment by bmillemathias** [comment] 2020-03-15 08:31
Yves Rocher are both shops and beauty saloon, but that's true they communicate more on the former than the latter.

**Comment by bmillemathias** [comment] 2020-03-15 08:50
actually dupe of #3603

**Comment by KAMI911** [comment] 2020-03-15 09:13
Yes you are right, only the minority of stores provide SPA/beauty services. Probably all stores with additional services are listed here: https://www.clicrdv.com/stores/yves-rocher-ca?locale=en

All stores are listed here:
https://storelocator.yves-rocher.eu/

**Comment by pyrog** [comment] 2020-04-06 07:04
Both links are dead 😉 
https://www.yves-rocher.fr/tout-sur-les-magasins/magasins-et-instituts-de-beauté/SL

**Comment by ArenaL5** [comment] 2020-06-02 12:38
Given that they have both shops with no beauty saloons, and beauty saloons with no shop, I went ahead and created a `brands/shop/cosmetics.json`. I also added `nomatch` tags.

**Closed** 2020-06-02 12:38 UTC
