### ISSUE TITLE
Amazon Hub with japanese tags being suggested in the US

### ISSUE THREAD

**Issue by tas50** [osmlab/name-suggestion-index#5790] opened 2021-12-04 19:43 UTC
Amazon Hub with japanese tags being suggested in the US

<img width="375" alt="Screen Shot 2021-12-04 at 11 41 59 AM" src="https://user-images.githubusercontent.com/1015200/144722552-143a463d-748e-4f37-b273-42430a2c9051.png">

**Comment by UKChris-osm** [comment] 2021-12-06 20:13
It doesn't seem to be just Amazon Hub Locker, this was within [Pennsylvania](https://www.openstreetmap.org/#map=18/40.66486/-76.64659)

![nsi-geoerror](https://user-images.githubusercontent.com/59393694/144914598-6c4abc21-6db9-4e3a-a27d-700e1601f573.png)

**Comment by UKChris-osm** [comment] 2021-12-06 20:29
If I click out of iD and re open it, the NSI seems to work as expected. Could it be that locationSets are just taking a long time to initialize in the background?

**Comment by arch0345** [comment] 2021-12-07 02:07
I think this is related to #5669 - like @UKChris-osm said it seems that it just takes awhile to filter the locationSets

**Comment by arch0345** [comment] 2021-12-07 04:24
I came across this same issue with this [Mobil in Tahiti](https://www.openstreetmap.org/node/5197250923):
![image](https://user-images.githubusercontent.com/85302075/144965626-077ba2dc-2bb0-4fb7-b75f-611997d18bfe.png)
I was updating the brand tags for other POIs for a few minutes before selecting this fuel station, so it doesn't seem to be caused by not having enough time to load in locationSets. Refreshing or reopening iD doesn't fix this either.

**Comment by bhousel** [comment] 2021-12-07 18:51
Yeah I'm pretty sure this is #5669 again.
This is a tricky thing to test.  What's supposed to happen is: after the files are loaded, the locationSets are indexed, then the user will only see locally correct presets.  Some of this work happens in the background.  This process seems to take a few seconds for me in Chrome.  

It's clearly taking longer or getting stuck for some people, but I don't know what's causing that.

For example, I tried testing it just now:
- Opened https://mapwith.ai/rapid (in USA)
- Immediately added a point
- Started typing "Amazon Hub" in the preset search screen.  I did see "Amazon Hub ロッカー" flash up on the screen sometime during the typing of <kbd>a</kbd><kbd>m</kbd><kbd>a</kbd><kbd>z</kbd><kbd>o</kbd>, but by the time I got to <kbd>n</kbd><kbd> </kbd><kbd>h</kbd><kbd>u</kbd> it was only offering me the English one.  Backspace some of the letters away, and I'm still getting the correctly filtered preset list.

I think I can add a fix to iD to make sure it just doesn't offer any suggestion presets at all while the service is still pending setup.

**Comment by LaoshuBaby** [comment] 2021-12-08 04:36
> If I click out of iD and re open it, the NSI seems to work as expected. Could it be that locationSets are just taking a long time to initialize in the background?

Yes, I tried 10 times with waiting for different time.

If I wait for more than 1 min, this problem will nolonger occur.

----
Is this problem a performance problem like this one? https://github.com/openstreetmap/iD/issues/8793

**Comment by UKChris-osm** [comment] 2021-12-11 09:48
> I think I can add a fix to iD to make sure it just doesn't offer any suggestion presets at all while the service is still pending setup.

I'm guessing as the features file grows, the process takes longer for the locationSets to be indexed within the users browser?

Maybe it's worth splitting the final index file into continents or something? As I never edit in Asia for example, having any of the NSI entries stored in my local cache are just taking up memory and processing power.

If I did pan over to Asia however, then iD could simply load the NSI file for that area in the background?

**Comment by bhousel** [comment] 2022-01-03 22:05
closing this here, and we can track on #5669

**Closed by bhousel** 2022-01-03 22:05 UTC
Labels: bug
