### ISSUE TITLE
Carris Metropolitana

### ISSUE THREAD

**Issue by DiogoBaptista98** [osmlab/name-suggestion-index#6553] opened 2022-05-05 14:17 UTC
Public transport brand (buses) in Lisbon Metropolitan Area, Portugal. It should be used in stops, platforms, bus lines.

https://www.wikidata.org/wiki/Q111611112

**Comment by bhousel** [comment] 2022-05-06 13:25
This looks like a duplicate of Carris, which we already have in the index:
https://nsi.guide/index.html?t=transit&k=route&v=bus#carris-d8d67b
https://www.wikidata.org/wiki/Q1045108

Is there a difference?

**Comment by DiogoBaptista98** [comment] 2022-05-06 13:32
Yes they are, Carris is the bus company in the municipal area of Lisbon, Carris Metropolitana is the new brand launched for all the buses on the Lisbon metropolitan area. More details in this news https://www.moveaveiro.pt/en/carris-metropolitana-presente-aujourdhui-entre-en-service-le-1er-juin

**Comment by bhousel** [comment] 2022-05-06 13:50
Ok thanks for clarifying!  I just added it as a network [just for the Lisbon area](https://location-conflation.com/?locationSet=%7B%20include%3A%20%5B%5B-9.2%2C%2038.8%2C%2045%5D%5D%20%7D%0A) based on their website.

**Closed** 2022-05-06 13:49 UTC

**Comment by DiogoBaptista98** [comment] 2022-05-06 18:29
> Ok thanks for clarifying! I just added it as a network [just for the Lisbon area](https://location-conflation.com/?locationSet=%7B%20include%3A%20%5B%5B-9.2%2C%2038.8%2C%2045%5D%5D%20%7D%0A) based on their website.

Thank you som much for the addition, but I can't see it on https://nsi.guide neither I can add it to the operator tag in the OSM id editor.

**Comment by bhousel** [comment] 2022-05-06 18:34
> Thank you som much for the addition, but I can't see it on https://nsi.guide neither I can add it to the operator tag in the OSM id editor.

yes it will appear in these places after we run the release script - we do this about once a week.
