### ISSUE TITLE
Support some sub-country regions (e.g. Canadian Province, US State)

### ISSUE THREAD

**Issue by lionirdeadman** [osmlab/name-suggestion-index#3162] opened 2019-10-27 19:40 UTC
Currently in Canada, Quebec vs English Canada entries are used when they are the same entity because of `name=*`, I think they could be all made into one if the NSI could determine which name it should use based on the location's language.

I don't know how possible that is but that would be nice.

**Comment by bhousel** [comment] 2019-10-31 16:10
Thanks for raising this - are there some brands where we get this wrong?

I'm not familiar with the local expectation here, but my guess is that adding both `name:en` and `name:fr` tags might be enough.  

For some entries we already do add multiple language tags where multiple local languages are commonly spoken (e.g. [things in Belarus commonly use both Russian and Belarusian](https://github.com/osmlab/name-suggestion-index/blob/cae541d89125ab376aaedddc7497b3933d541664/brands/amenity/post_office.json#L354-L370))

**Comment by bhousel** [comment] 2019-10-31 16:44
I took care of National Bank of Canada, but if you find any more please open an issue and I'll take care of it 👍

**Comment by lionirdeadman** [comment] 2019-11-02 17:35
The problem with choosing `name=*` as only english or another language is that `name=*` is supposed to represent what's on the ground, the localized name, at least that's been my understanding of it. 

And for the examples of National Bank and Desjardins is that in Quebec unlike the rest of Canada, French is *always* used exclusively or 10% bigger than the english name as per Bill 101.

So making them both as the same entry without making the NSI know which localization should be used for `name=*`, it creates huge inaccuraties as the NSI is used more and more..

**Comment by bhousel** [comment] 2019-11-03 01:40
Ok well, let me know what to do.  I'm totally ok with combining them into a single entry, or having 2 and people can choose.  I thought you wanted me to combine them.  

We don't currently have a way to scope a brand to anything smaller than the country level, but it's something we're thinking about.

**Comment by lionirdeadman** [comment] 2019-11-03 02:01
Well, this issue was to have the ability to have them in one but respect localization beyond on a country-level but since this is something you're already thinking about, I guess it's fair to close this issue and put them back as two different entries and let people choose until it's possible to combine them in a way which respects localization beyond the country-level.

Where can I track the issue on scoping things smaller than the country level?

Thanks and sorry for the quite late response ^^'

**Comment by bhousel** [comment] 2019-11-04 18:31
> Where can I track the issue on scoping things smaller than the country level?

Let's leave this issue open for it..

**Comment by bkissin** [comment] 2019-11-22 01:23
One thing I've run into working on Quebec tags is that **Staples** in Quebec is **Bureau en Gros**

Additionally, some communities that are really into Bill 101 will have **KFC** listed as **PFK** (Poulet Frit Kentucky). I've been tagging them as the regular source but then renaming the feature to fit the local environment.

**Comment by bhousel** [comment] 2019-11-22 01:44
I started a thing today that I hope will make it easy to define complex regions, since this has become thing I want for several projects.   
https://github.com/ideditor/location-conflation

**Comment by bhousel** [comment] 2020-06-03 02:44
> I started a thing today that I hope will make it easy to define complex regions, since this has become thing I want for several projects.
> https://github.com/ideditor/location-conflation

☝️  FYI, I'm planning to do this in the next few days.  This approach has worked pretty well in the [osm-community-index](https://github.com/osmlab/osm-community-index/) and [imagery-index](https://github.com/ideditor/imagery-index) projects.   

This is why I'm trying to clear out all the outstanding PRs.  This change will affect how we store `countryCodes` and will be breaking across all the files.

**Comment by bhousel** [comment] 2020-06-08 11:46
But I didnt actually do the thing the issue is about yet

**Comment by Adamant36** [comment] 2020-06-08 14:42
My bad. I thought you did.

**Comment by bhousel** [comment] 2020-06-18 14:20
Hey @lionirdeadman I'd like to close this issue now that we have the ability to limit a brand to a sub-country region.  Is it correct to say that these brands should be in French only in Quebec?

**Comment by lionirdeadman** [comment] 2020-06-18 16:38
That is correct, `name=*` should be French-only. (I assume `name:en=*` remains unchanged)

**Comment by bhousel** [comment] 2020-06-18 21:11
@lionirdeadman - can you check that last commit c7373e4 ? 
I split the national bank brand back into 2 entries:
- "National Bank" for all of Canada except Quebec
- "Banque Nationale" for just Quebec

Does this approach look alright?  If so, we can do this for the other brands you and @bkissin  mentioned.

**Comment by lionirdeadman** [comment] 2020-06-19 00:33
That seems good. I'm not familiar with how the code works but it seems right to me. Although, I thought the ideal model would've simply had the nsi pick `name:en` or `name:fr` based on geolocation rather than keeping them duplicated?

**Closed** 2020-09-22 19:03 UTC
Labels: enhancement
