### ISSUE TITLE
Publish a new release or otherwise ensure iD can import recent updates to the NSI

### ISSUE THREAD

**Issue by rjw62** [osmlab/name-suggestion-index#4543] opened 2020-10-20 13:27 UTC
I see that this project hasn't published a release since v4.0.2 in April 2020. I assume that this is why iD hasn't updated its version of the NSI since that time. iD is thus not taking advantage of more recent updates to the NSI, and more importantly is continuing to entice mappers to make erroneous changes based on mistakes in that release of the NSI that have since been fixed.

I understand that there have been some changes to the output format of the NSI, which may cause problems for new releases and imports by iD. Nevertheless, I think something needs to be done between this project and iD to ensure that new releases can be made and will feed in to iD in a timely manner.

**Comment by bhousel** [comment] 2020-10-20 13:39
I agree, we should release a new version soon.  The next published version of NSI will be a major release with breaking changes, so nothing will happen really quickly.. But I do expect to be able to push an update to iD in the next month or so.

**Comment by TheAdventurer64** [comment] 2020-12-23 20:38
Regarding this, GoMap has the newest changes to the NSI, while iD is still using outdated presets.

**Comment by quincylvania** [comment] 2021-01-04 15:25
@TheAdventurer64 That's nice for GoMap, but keep in mind that iD's update cycle isn't tied to any other editor. In open source, things get done when they get done 🤷

**Comment by bhousel** [comment] 2021-03-04 14:27
We're pretty close on this!
I deployed an iD with the preview NSI v5 code to:  http://www.ideditor.org/nsi-v5/
Try it out and let me know if you find any odd validation suggestions.

**Comment by kjonosm** [comment] 2021-03-04 17:57
> let me know if you find any odd validation or preset suggestions!

Hotel name validation seems to strict:
![Bildschirmfoto 2021-03-04 um 18 53 32](https://user-images.githubusercontent.com/51236777/110007559-1849a280-7d1b-11eb-8f07-646cb4d81326.png)

**Comment by kjonosm** [comment] 2021-03-04 18:05
Validator warning generally refers to an outdated or incomplete **brand** (**Marke** in German) instead of an outdated or incomplete **network** or **operator**:

![image](https://user-images.githubusercontent.com/51236777/110008217-c0f80200-7d1b-11eb-9581-00ebb346f824.png)

**Comment by kjonosm** [comment] 2021-03-04 18:11
Validator still wants to update supermarket name although `brand` tag is already correctly set:

![Bildschirmfoto 2021-03-04 um 19 08 19](https://user-images.githubusercontent.com/51236777/110009253-0c5ee000-7d1d-11eb-930d-f5df62791f29.png)

**Comment by kjonosm** [comment] 2021-03-04 18:29
Nextbike operates several differently branded bike sharing systems across Europe. The validator seems to check for matching `operator` tags and wants to update to the wrong brand. For [this](https://www.openstreetmap.org/node/7355134843) example id should update to [Edeka nextbike](https://nsi.guide/index.html?t=brands&k=amenity&v=bicycle_rental&cc=de#edekanextbike-937152):

![image](https://user-images.githubusercontent.com/51236777/110010637-cf93e880-7d1e-11eb-97a9-e8ea99fe8fef.png)

**Comment by kjonosm** [comment] 2021-03-04 18:59
weird update suggestion for a stamp vending machine apparently based on matching operator, see [here](https://www.openstreetmap.org/node/3163345370)

![Bildschirmfoto 2021-03-04 um 19 56 11](https://user-images.githubusercontent.com/51236777/110015019-bb061f00-7d23-11eb-9094-ba776befff72.png)

**Comment by kjonosm** [comment] 2021-03-04 19:14
Wrong update suggestion for the `network` values of [this](https://www.openstreetmap.org/relation/319058) relation. Maybe only match features with matching `network` tag and ignore matching `operator` tags.

![Bildschirmfoto 2021-03-04 um 20 04 38](https://user-images.githubusercontent.com/51236777/110016276-200e4480-7d25-11eb-91da-c1b1e7f45305.png)

**Comment by bhousel** [comment] 2021-03-04 19:19
Thanks for testing @kjonosm !
> Hotel name validation seems to strict:

Good catch, I was missing the `preserveNames` property on these.  I'll push an update to the NSI `dist/*` files shortly.

>Validator warning generally refers to an outdated or incomplete brand (Marke in German) instead of an outdated or incomplete network or operator:

Oh yeah, this is a localization issue that will be updated on the iD side eventually.. The new English source strings are a bit broader: 
```js
noncanonical_brand:
  message: "{feature} looks like a common feature with nonstandard tags"
  message_incomplete: "{feature} looks like a common feature with incomplete tags"
  reference: "Some features, for example retail chains or post offices, are expected to have certain tags in common."
```

>Validator still wants to update supermarket name although brand tag is already correctly set:

Yea this is a lot like the Tesco example [here](https://github.com/osmlab/name-suggestion-index/issues/4906#issuecomment-781442422).  Do you think people would be ok if the validator offered tagging like `name=Edeka`+`branch=Barnimstraße`?   The osm wiki does encourage it, so it seems like it would be a reasonable suggestion.

(will respond to others soon.. )

**Comment by kjonosm** [comment] 2021-03-04 19:36
> Do you think people would be ok if the validator offered tagging like name=Edeka+branch=Barnimstraße?

I can't say. I personally don't have a strong opinion about it but if `branch=*` was an "approved" key there might be more people willing to accept this tagging style.

**Comment by bhousel** [comment] 2021-03-04 20:25
> I personally don't have a strong opinion about it but if `branch=*` was an "approved" key there might be more people willing to accept this tagging style.

From https://wiki.openstreetmap.org/wiki/Key:branch it looks like it's used >150,000 times, so it seems ok to me..

**Comment by bhousel** [comment] 2021-03-05 16:37
Thanks again @kjonosm , 
Capturing the feedback from above.. I've made a bunch of fixes and pushed a new version to http://www.ideditor.org/nsi-v5/

- [x] "Hotel validation too strict" - Fix missing Hotel/Motel preserveTags (fixed in NSI)
- [x] "Validator wants to upgrade Edeka supermarket name" - Now offers to split into `name` and `branch` (fixed in iD pull request)
- [x] "Weird update suggestion for a stamp vending machine" - This was improperly considering `amenity/yes` as an alternate match (Fixed in iD pull request, also added an entry for this vending machine in NSI)
- [x] "Wrong update suggestion for network" - Don't try any matching or upgrade if any of the namelike values contain semicolons (Fixed in iD pull request)
- [ ]  I still have to look into the nexbike issue

**Comment by bhousel** [comment] 2021-03-05 22:33
> Nextbike operates several differently branded bike sharing systems across Europe. The validator seems to check for matching `operator` tags and wants to update to the wrong brand. For [this](https://www.openstreetmap.org/node/7355134843) example id should update to [Edeka nextbike](https://nsi.guide/index.html?t=brands&k=amenity&v=bicycle_rental&cc=de#edekanextbike-937152):

I looked into that nextbike a bit, you are correct that it's matching on the `operator=nextbike` tag, and it looks like the matcher understands these to be viable candidates (based on the operator/brand tags in NSI):
![Screen Shot 2021-03-05 at 5 08 16 PM](https://user-images.githubusercontent.com/38784/110179079-763ac080-7dd5-11eb-9e4d-ac4ca8f8bc1a.png)

["Edeka Nextbike"](https://nsi.guide/index.html?t=brands&k=amenity&v=bicycle_rental#edekanextbike-937152) doesn't have a `brand:wikidata` tag, so it skips over that one and perfers the ["metropolradruhr"](https://nsi.guide/index.html?t=brands&k=amenity&v=bicycle_rental&tt=nextbike#metropolradruhr-937152) one.

I notice that the bike share page has "nextbike" as a named exclude:
https://github.com/osmlab/name-suggestion-index/blob/63c6b02efb366f31ef63c6b07d84c7bef5bbfa8d/data/brands/amenity/bicycle_rental.json#L2-L11

So I might need to adjust something in NSI.  I wasn't really expecting that things specifically excluded could also be used as tag values.

**Comment by bhousel** [comment] 2021-03-05 23:03
> So I might need to adjust something in NSI. I wasn't really expecting that things specifically excluded could also be used as tag values.

I made a change in the matcher to not index the excluded values (like "nextbike"), so that should take care of this issue!

@kjonosm thanks again, and let me know if things look better on  http://www.ideditor.org/nsi-v5/

**Comment by kjonosm** [comment] 2021-03-06 11:03
I don't know what happens [here](https://www.openstreetmap.org/node/69226073) but removing the `surveillance` tag seems too strict.

![image](https://user-images.githubusercontent.com/51236777/110204486-8dc88680-7e73-11eb-8be4-62724bf9b337.png)

**Comment by kjonosm** [comment] 2021-03-06 11:14
Not really a validation issue but is it possible/desirable to show the operator logo if a brand logo is missing? See [here](https://www.openstreetmap.org/node/3751697051) for example, where it would be nice to see a DHL logo when selecting the object in iD. This might also be an improvement for networks with missing logos...
![image](https://user-images.githubusercontent.com/51236777/110204771-2c091c00-7e75-11eb-9053-df0ee685790a.png)

**Comment by kjonosm** [comment] 2021-03-06 11:26
Please mention the feature type in validator text to make it less confusing for users. [Here](https://www.openstreetmap.org/node/459466301) it would be useful to give a hint that the issue is about a mailbox (Briefkasten in German).

![image](https://user-images.githubusercontent.com/51236777/110205182-21e81d00-7e77-11eb-9acb-26d61dc139a1.png)

![image](https://user-images.githubusercontent.com/51236777/110205037-92426e80-7e76-11eb-8f02-eb02010816b8.png)

**Comment by kjonosm** [comment] 2021-03-06 11:53
The name suggestion for car-sharing stations seems too strict as most stations tend to have a unique name (like amazon lockers). See [here](https://www.openstreetmap.org/node/2059453018) for example. For this operator I already removed the name tag in nsi.

![image](https://user-images.githubusercontent.com/51236777/110205735-1ba77000-7e7a-11eb-8efb-7f38fcaa289c.png)

**Comment by kjonosm** [comment] 2021-03-06 12:18
It seems like id uses the nsi `displayName` value for the feature label, e.g. "Postbank (Germany)" in [this](https://www.openstreetmap.org/node/647081922) example. I stumbled upon the brackets and wondered whether for iD it made more sense to instead just use the feature's `brand` value to make it less confusing for users?

![image](https://user-images.githubusercontent.com/51236777/110206215-bb65fd80-7e7c-11eb-89c5-e84c0c8c3d7f.png)

**Comment by kjonosm** [comment] 2021-03-06 13:26
Many transit routes in nsi have an `operator` tag that often wrongly duplicates the `network` tag. I cleaned up lots of these in nsi already but there still are many routes where the validator suggests to remove valid `operator` data, like in [this](https://www.openstreetmap.org/relation/8337481) example.

This happens because (as recommended by osm wiki) in many countries `network` is used to tag the transit district often consisting of several different transport companies licensed to operate in.

![image](https://user-images.githubusercontent.com/51236777/110207672-5fec3d80-7e85-11eb-8ce8-2c05c38850e5.png)

**Comment by kjonosm** [comment] 2021-03-06 14:03
[This](https://www.openstreetmap.org/node/3804579488) example shows a shop where the branch name doesn't denote the location but the franchisee. In this context `branch=Klein` looked odd to me and made me wonder, whether it might generally be better to use the entire name for `branch` as in `branch=Expert Klein` despite slightly deviating from the osm-wiki recommendation.

![image](https://user-images.githubusercontent.com/51236777/110209070-c0ca4480-7e8a-11eb-90ed-4230497957f6.png)

**Comment by bhousel** [comment] 2021-03-08 14:48
Thanks @kjonosm, I'll work through these issues today: 
- [ ] Don't remove `man_made=surveillance` tag (same issue we have with `pharmacy` tag here https://github.com/openstreetmap/iD/pull/8305#issuecomment-790028237)
- [ ] DHL Logo fallback?  We can't easily fallback to the operator logo, but I can at least make sure Wikidata has something for DHL Packstation
- [ ] Please mention the feature type in validator text (I agree!)
- [ ] NSI `displayName` value for the feature label, e.g. "Postbank (Germany)"  - We don't have an easy way to change this, but we could have the `displayName` in the local language, like "Postbank (Deutchland)" so that it looks less weird to a German speaker?
- [ ] The `operator`/`network` thing - (I don't really understand it)
- [ ] @kjonosm - Where splitting of `name` into `name`/`branch` looks wrong - are these examples where we should just leave name alone?  (like Pubs, Hotels, Apple Stores, Amazon Lockers)? We can do that too.  I don't know these brands well enough to decide it..

**Comment by kjonosm** [comment] 2021-03-08 19:50
> The operator/network thing - (I don't really understand it)

For each transit network collected from the planet, the `operator` value is automatically added by just duplicating the `network` value. In many cases this is a mistake and leads to wrong data. See e.g. following networks where the operator tag in nsi is just a copy of the network tag, deviating from the actual tagging in OSM you can compare in the given overpass turbo links:

- [AMI Ferrara](https://overpass-turbo.eu/s/14P9)
- [aMo - Città di Sassuolo](https://overpass-turbo.eu/s/14Pa)
- [Amstelland-Meerlanden](https://overpass-turbo.eu/s/14Pb)
- [Andante](https://overpass-turbo.eu/s/14Pc)

iD validator now suggests to update the existing and correctly tagged `operator` value with this wrongly collected `operator` value.

**Comment by kjonosm** [comment] 2021-03-08 20:05
> are these examples where we should just leave name alone?

Hard to say. I don't really mind the shortened `name` tag. It's the `branch` tag that somehow looks odd to me, hence my suggestion to just copy the entire string to the `branch` value.
In addition, for the examples where the franchisee makes part of the name (Intersport Voswinkel, Expert Klein) it's technically not a (unique) branch name as both franchisees to my knowledge own more than one shop.

**Comment by bhousel** [comment] 2021-03-08 20:24
> For each transit network collected from the planet, the `operator` value is automatically added by just duplicating the `network` value. In many cases this is a mistake and leads to wrong data. See e.g. following networks where the operator tag in nsi is just a copy of the network tag, deviating from the actual tagging in OSM you can compare in the given overpass turbo links:

Ah yeah I see now.  Since so many are wrong, I think I'm just going to remove all the `operator` values from the transit tree, and people will need to put them back manually.  This is annoying and I feel bad about it, but at least it will prevent the validator from pushing wrong tags.  I'm going to open a new issue for it, so everyone knows..

**Comment by bhousel** [comment] 2021-03-08 22:50
I pushed the latest work to https://ideditor.org/nsi-v5  - let me know what you think!

The way I'm looking at the `name`/`branch` thing is - splitting the name up is better than overwriting the name because then data doesn't get lost.  I'd like to let people test for another week or so and see what people think. 

We can also definitely leave the name alone on a per-category or per-item basis..

**Comment by kjonosm** [comment] 2021-03-09 21:29
Weird validator message for [this](https://www.openstreetmap.org/node/2316880216) shop (feature name comes up twice).

![image](https://user-images.githubusercontent.com/51236777/110540282-95fc1c80-8126-11eb-8e57-bc2bdc389ff0.png)

**Comment by bhousel** [comment] 2021-03-09 22:14
@kjonosm do you mean how the message says "Saturn Saturn..." (which I agree is weird).

**Comment by kjonosm** [comment] 2021-03-09 23:05
> We can display the non-verbose version of the message if the preset is a suggestion preset.

Yes, that should work. Thanks!

**Comment by bhousel** [comment] 2021-03-10 15:36
> Yes, that should work. Thanks!

Great - it looks like this now.. I agree it's much better 👍 

<img width="450" alt="Screen Shot 2021-03-10 at 10 35 30 AM" src="https://user-images.githubusercontent.com/38784/110654775-6e3f9f80-818c-11eb-9326-5f835bd8ef22.png">

**Comment by kjonosm** [comment] 2021-03-10 21:17
The Nextbike issue shows up again, see [this node](https://www.openstreetmap.org/node/1660858842)
I have to say I don't really know how to properly tag these nextbike schemes myself.
They run several different business models, see their [website](https://www.nextbike.de/en/locations/)

![image](https://user-images.githubusercontent.com/51236777/110697499-b8f10400-81ec-11eb-9f4b-212a7923c088.png)

**Comment by kjonosm** [comment] 2021-03-11 12:27
Weird validator message at bottom of the screenshot for [this](https://www.openstreetmap.org/node/440072689) feature

![Bildschirmfoto 2021-03-11 um 13 24 50](https://user-images.githubusercontent.com/51236777/110787130-47a56580-826d-11eb-84e0-9e6152571217.png)

**Comment by bhousel** [comment] 2021-03-11 22:59
Thanks again @kjonosm - I think I've fixed the 2 issues above, can you refresh  https://ideditor.org/nsi-v5  and test again when you have some time?

- [x] I fixed the weird error message (incidentally, it is a warning that this feature shouldn't be a point on the edge of another feature - I'm not sure whether this message is really a fair issue, as I know a few mappers like to put POIs on building entrances - but in any case extracting the shop to its own standalone point fixes it)
- [x] after nextbike is recognized as a generic name, the matcher will stop looking (what it was doing before was falling back to a match on `brand:wikidata` qid.)

**Comment by kjonosm** [comment] 2021-03-12 15:52
The validator doesn't suggest a `branch` tag for [this](https://www.openstreetmap.org/way/158559043) bank. Maybe the comma in the `name` tag is causing this?

![image](https://user-images.githubusercontent.com/51236777/110964124-23bc4f80-8353-11eb-85f1-92b20a81e597.png)

**Comment by bhousel** [comment] 2021-03-12 21:03
> Maybe the comma in the `name` tag is causing this?

Yeah, that was it - I rewrote the name/branch splitting code this morning to make it more reliable.

**Comment by kjonosm** [comment] 2021-03-15 20:34
name/branch splitting needs some adjustment. [Here](https://www.openstreetmap.org/node/2529745222) the code creates an empty value...

![image](https://user-images.githubusercontent.com/51236777/111217495-e6b3bf80-85d5-11eb-8ea2-09eb9c0af171.png)

**Comment by bhousel** [comment] 2021-03-24 22:11
I've been doing a bunch of testing with this the past few days, and I think it's about as good as it will get.. NSI v5 has been published, and the test branch below will pull the latest version.. I'd love for more people to test here and let me know if you notice any issues:
https://ideditor.org/nsi-v5

**Closed by bhousel** 2021-03-24 22:11 UTC
Labels: news
